---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# LAPP

Ligand Analysis with Physiochemical Properties (LAPP) is a small package I made to study HLA peptidomes. It has various functions for data conversion, visualization, and prediction. 

## Installation

You can install LAPP in R with the following commands

```{r install, eval=FALSE}
library(devtools)
devtools::install_github("ash129/LAPP")
```

## Usage

The vignette is still under construction. Check again soon!

```{r vignette, dev='png', fig.width=9, fig.height=9}
library(penrose)

# parameters
core.x= 0 # center x
core.y= 0 # center y
core.r= 500 # radius
final.iter= 7 # number of times to deflate


# no margins
op= par(mar = rep(0, 4))

# set up plot
plot(1, type= "n", xaxt="n", yaxt="n", ann=FALSE, frame.plot= FALSE, 
     xlim=c(-core.r, core.r)*0.85 , 
     ylim=c(-core.r, core.r)*0.85 )

# black backdrop
polygon(c(-core.r, -core.r, core.r, core.r)*2 + core.x, c(core.r, -core.r, -core.r, core.r)*2 + core.y, col= "black")

# penrose
penrose.full(core.x= core.x, core.y= core.y, core.r= core.r, final.iter= final.iter, 
             kite= TRUE, dart= TRUE, core.rot= 0, core.sca= 1, cent.rot= 0, cent.sca= 1)

```
